import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Providers from "@/components/layout/Providers";
import TopMenu from "@/components/layout/TopMenu";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es" className="min-h-screen overflow-x-hidden">
      <body className={`${inter.className} h-full`}>
        <Providers>
          <TopMenu />
          <div className="container mx-auto px-3">
            {children}
          </div>
        </Providers>
      </body>
    </html>
  );
}
